remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jpa_v3_0]
description: [Jakarta EE Persistence API Technology Compatibility Kit User's Guide, Release 3.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://jakarta.ee/specifications/persistence/3.0/
  #mailinglist: https://javaee.groups.io/g/tck_jpa_v2_2
  javadocs: https://jakarta.ee/specifications/persistence/3.0/
  docs: https://jakarta.ee/specifications/persistence/3.0/
  #faq:

