remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jaxws_v3_0]
description: [Oracle Java API for Web Services (JAX-WS) Technology Compatibility Kit User's Guide for Technology Licensees, Release 3.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jax-ws-api
  download: https://github.com/eclipse-ee4j/jax-ws-api/releases/tag/3.0.0-RC3
  #mailinglist: https://javaee.groups.io/g/tck_jaxws_v2_3
  #javadocs:
  # https://eclipse-ee4j.github.io/jax-ws-api is missing
  docs: https://projects.eclipse.org/projects/ee4j.jaxws
  #faq:
