remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_soap_v2_0]
description: [Oracle Technology Compatibility Kit User's Guide for Java API for Jakarta SOAP with Attachments 2.0 for Technology Licensees, Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/saaj-api
  download: https://github.com/eclipse-ee4j/saaj-api/releases/tag/2.0.0
  #mailinglist: https://javaee.groups.io/g/tck_jaxrs_v2_1
  #javadocs:
  # https://eclipse-ee4j.github.io/saaj-api is missing
  docs: https://projects.eclipse.org/projects/ee4j.jaxws
  #faq:
