remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jsonp_v2_0]
description: [Oracle Technology Compatibility Kit User's Guide for Java API for JSON Processing 2.0 for Technology Licensees, Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jsonp
  download: https://github.com/eclipse-ee4j/jsonp/releases/tag/2.0.0-RELEASE
  #mailinglist: https://javaee.groups.io/g/tck_jsonp_v1_1
  #javadocs:
  docs: https://eclipse-ee4j.github.io/jsonp
  #faq:
